server:
  port: 8020
  tomcat:
    uri-encoding: UTF-8
    min-spare-threads: 20
#=====================================  spring  =============================
spring:
  application:
    name: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 52428800
      max-request-size: 52428800
  #时区
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#=====================================  ali yun  ==============================
ali-yun:
  oss:
    bucket-name: "xxx"
    endpoint: "xxx"
    key-id: "xxx"
    key-secret: "xxx"
    file-host: "xxx"
